# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kcal', models.IntegerField()),
                ('food_category', models.IntegerField(choices=[(1, 'breakfast'), (2, 'brunch'), (3, 'dinner'), (4, 'supper')])),
                ('protein', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('carbohydrate', models.FloatField(null=True)),
                ('roughage', models.FloatField(null=True)),
                ('sugar', models.FloatField(null=True)),
            ],
        ),
    ]
