# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietmanager', '0003_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='height',
            field=models.FloatField(),
        ),
    ]
