# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dietmanager', '0004_auto_20170719_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gda', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('sex', models.FloatField(choices=[(1.0, 'Man'), (0.9, 'Woman')])),
                ('activity', models.FloatField(choices=[(1.0, 'Small activity, sitting job'), (1.1, 'Sporadic activity(once a week), sitting job'), (1.2, 'Activity 1-2 times a week, sitting job'), (1.3, 'Intense activity (eg. fitness) 2-3 times a week, sitting job'), (1.4, 'Activity everyday (eg. fitness, joggin), job requires movement'), (1.5, 'Doing lot of movement all the time, physical job')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
